from pathlib import Path
p=Path('/mnt/data/rolefix/app.py')
s=p.read_text()
# 1. Add guest request session tracking in create_request by replacing block that auto assigns
old='''    conn=db(); rid=None; best=None\n    try:\n        conn.execute('BEGIN IMMEDIATE')\n        t=now()\n        cur=conn.execute('INSERT INTO requests(customer_id,guest_name,service,pickup_name,destination_name,pickup_lat,pickup_lon,dest_lat,dest_lon,fare,payment,status,created_at,updated_at,item_count,helper_count) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(a['id'] if a else None,guest,service,pickup.get('name','Pickup'),dest.get('name','Destination'),pickup['lat'],pickup['lon'],dest['lat'],dest['lon'],fare,data.get('payment','Cash'),'requested',t,t,int(data.get('item_count') or 0),int(data.get('helper_count') or 0)))\n        rid=cur.lastrowid\n        scored=partner_candidates(conn,service,float(pickup['lat']),float(pickup['lon']))\n        if scored:\n            _,_,candidate=scored[0]\n            changed=conn.execute("UPDATE partners SET status='green' WHERE id=? AND status='orange'",(candidate['id'],)).rowcount\n            if changed:\n                conn.execute("UPDATE requests SET partner_id=?,status='assigned',updated_at=? WHERE id=?",(candidate['id'],t,rid)); best=candidate\n        conn.execute('COMMIT')\n    except Exception:\n        try: conn.execute('ROLLBACK')\n        except Exception: pass\n        add_error('server','/api/request',500,'POST','Could not create request')\n        return jsonify(ok=False,error='Unable to create request'),500\n    return jsonify(ok=True,id=rid,fare=fare,assigned=best['name'] if best else None,status='assigned' if best else 'requested')'''
new='''    conn=db(); rid=None\n    try:\n        conn.execute('BEGIN IMMEDIATE')\n        t=now()\n        cur=conn.execute('INSERT INTO requests(customer_id,guest_name,service,pickup_name,destination_name,pickup_lat,pickup_lon,dest_lat,dest_lon,fare,payment,status,created_at,updated_at,item_count,helper_count) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(a['id'] if a else None,guest,service,pickup.get('name','Pickup'),dest.get('name','Destination'),pickup['lat'],pickup['lon'],dest['lat'],dest['lon'],fare,data.get('payment','Cash'),'requested',t,t,int(data.get('item_count') or 0),int(data.get('helper_count') or 0)))\n        rid=cur.lastrowid\n        conn.execute('COMMIT')\n    except Exception:\n        try: conn.execute('ROLLBACK')\n        except Exception: pass\n        add_error('server','/api/request',500,'POST','Could not create request')\n        return jsonify(ok=False,error='Unable to create request'),500\n    if not a:\n        ids=session.get('guest_request_ids',[])\n        ids=(ids+[rid])[-20:]\n        session['guest_request_ids']=ids\n    return jsonify(ok=True,id=rid,fare=fare,assigned=None,status='requested')'''
if old not in s: raise SystemExit('create_request block not found')
s=s.replace(old,new)
# 2. Replace request_status auth condition with guest session allowance
old="""    a=actor()\n    if not session.get('admin') and (not a or (a['role']=='customer' and r['customer_id']!=a['id']) or (a['role']=='partner' and r['service']!=a['service'])): return jsonify(ok=False),403\n    return jsonify(dict(r))\n"""
new="""    a=actor()\n    guest_allowed = (not a and rid in session.get('guest_request_ids', []))\n    if not session.get('admin') and not guest_allowed and (not a or (a['role']=='customer' and r['customer_id']!=a['id']) or (a['role']=='partner' and r['service']!=a['service'])): return jsonify(ok=False),403\n    return jsonify(dict(r))\n"""
if old not in s: raise SystemExit('request_status auth not found')
s=s.replace(old,new)
# 3. Make partner dashboard choose distinct templates and compute notification/open counts
old="""    return render_template('partner.html',sidebar=nav('partner',service),partner=p,requests=reqs,friends=friends,service=service,service_name=SERVICES[service],page_theme='light')\n"""
new="""    template = {'ride':'partner_ride.html','drive':'partner_drive.html','mover':'partner_mover.html'}[service]\n    return render_template(template,sidebar=nav('partner',service),partner=p,requests=reqs,friends=friends,service=service,service_name=SERVICES[service],page_theme='light')\n"""
if old not in s: raise SystemExit('partner render not found')
s=s.replace(old,new)
# 4. Add live requests API before partner requests route
marker="""@app.get('/partner/requests')\n@login_required('partner')\ndef partner_requests(): return redirect(url_for('partner_home',service=actor()['service']))\n"""
insert="""@app.get('/api/partner/live')\n@login_required('partner')\ndef partner_live():\n    a=actor(); p=q('SELECT p.*,a.name,a.phone FROM partners p JOIN accounts a ON a.id=p.account_id WHERE p.account_id=?',(a['id'],),True)\n    if not p: return jsonify(ok=False),404\n    open_rows=q(\"SELECT r.id,r.service,r.pickup_name,r.destination_name,r.pickup_lat,r.pickup_lon,r.dest_lat,r.dest_lon,r.fare,r.payment,r.status,r.created_at,COALESCE(a.name,r.guest_name,'Mteja') customer_name,COALESCE(a.phone,'') customer_phone FROM requests r LEFT JOIN accounts a ON a.id=r.customer_id WHERE r.service=? AND ((r.partner_id=? AND r.status IN ('assigned','on_trip')) OR (r.partner_id IS NULL AND r.status='requested')) ORDER BY r.created_at ASC LIMIT 80\",(p['service'],p['id']))\n    out=[]\n    for r in open_rows:\n        d=None\n        if p['lat'] is not None and p['lon'] is not None and r['pickup_lat'] is not None and r['pickup_lon'] is not None:\n            d=math.hypot((r['pickup_lat']-p['lat'])*111,(r['pickup_lon']-p['lon'])*111*math.cos(math.radians(float(p['lat']))))\n        item=dict(r); item['distance_km']=round(d,2) if d is not None else None; item['mine']=(r['partner_id'] if 'partner_id' in r.keys() else None)==p['id']\n        out.append(item)\n    nearby=\n        [dict(x) for x in q(\"SELECT p.id,p.service,p.status,p.lat,p.lon,p.speed_kmh,a.name FROM partners p JOIN accounts a ON a.id=p.account_id WHERE p.service=? AND p.id!=? AND a.active=1 AND p.lat IS NOT NULL AND p.lon IS NOT NULL\",(p['service'],p['id']))]\n    return jsonify(ok=True,partner=dict(p),requests=out,partners=nearby,server_time=now())\n\n\n@app.get('/partner/requests')\n@login_required('partner')\ndef partner_requests(): return redirect(url_for('partner_home',service=actor()['service']))\n"""
if marker not in s: raise SystemExit('partner requests marker not found')
s=s.replace(marker,insert)
p.write_text(s)
